### ISSUE TITLE
External links are showed as internal links

### ISSUE THREAD

**Issue by tuxpeople** [getmatterapp/obsidian-matter#24]
In the metadata part of the generated note, there's a link back to the publisher. Unfortunately, it looks like it's formatted as an internal link. Example:

```
* Publisher: [[www.heise.de]]
```

The link should contain the protocol, so Obsidian discovers it as e external link:

```
* Publisher: [www.heise.de](https://www.heise.de)
```

**Comment by tuxpeople** [comment]
hmm... Maybe, it's a feature, not a bug. As it's an internal Link, it can be used to group Articles from the same publisher.

**Comment by hunterclarke** [comment]
Thanks for the report. You're exactly right. The `Publisher` field is meant to be helpful for organizing writing within your Obsidian vault. In order to visit the publisher, you can just use the link to the article to view it in your browser.

In this case it's a little confusing because we weren't able to pull a publisher name for this article, so we present it as a url. However, for most other articles you should see that the publisher is something like `The New York Times`.
