### ISSUE TITLE
split sync into two obsidian vaults based on hashtags

### ISSUE THREAD

**Issue by iamrobmat** [getmatterapp/obsidian-matter#44]
hey,

I have 2 vaults for 
1. personal use (journaling, health, personal development, psychology, etc) 
2. work vault (software, business etc)

I would like to sync articles from matter based on specific hashtag to one of my vaults.

for example article tagged:
- health > would sync to vault 1
- software > would sync to vault 2

is that possible to setup?

**Comment by hunterclarke** [comment]
Hey @iamrobmat

Obsidian installs plugins at the vault level, so it's not possible for the plugin to know about multiple vaults. The only way I could see this working in the future is to install the plugin in both vaults, then we have some kind of filtering ability that allows you to select which highlights to sync from Matter. But that's not currently on the roadmap. Most folks want to sync everything to the vault they are looking at.

I could be convinced otherwise. So I'll keep an eye on this over the next few weeks and see what the community says.

Thanks for message!
